-- ============================================================================
-- Migration: Create Roles Table
-- Description: Cria tabela de roles (papéis) do sistema
-- Author: Generated by AI Coding Process
-- Date: 2024-01-01
-- ============================================================================

-- Criar tabela de roles
CREATE TABLE IF NOT EXISTS public.roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  permissions JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comentários na tabela
COMMENT ON TABLE public.roles IS 'Armazena os papéis/permissões disponíveis no sistema';
COMMENT ON COLUMN public.roles.name IS 'Nome único do papel (ex: user, admin, moderator)';
COMMENT ON COLUMN public.roles.permissions IS 'Permissões do papel em formato JSON';

-- Índices
CREATE INDEX IF NOT EXISTS idx_roles_name ON public.roles(name);

-- Inserir roles padrão
INSERT INTO public.roles (name, description, permissions) VALUES
  ('user', 'Usuário padrão do sistema', '{"read": true, "write": true}'),
  ('admin', 'Administrador com acesso total', '{"read": true, "write": true, "delete": true, "admin": true}'),
  ('moderator', 'Moderador com permissões extras', '{"read": true, "write": true, "delete": true}')
ON CONFLICT (name) DO NOTHING;

-- Habilitar Row Level Security
ALTER TABLE public.roles ENABLE ROW LEVEL SECURITY;

-- Policy: Todos podem ler roles
CREATE POLICY "Anyone can read roles"
  ON public.roles FOR SELECT
  USING (true);

-- Policy: Apenas admins podem modificar roles (será implementado depois que users existir)
-- Essa policy será atualizada na migration 20240101000003

-- ============================================================================
-- Verificação
-- ============================================================================
-- Executar para verificar:
-- SELECT * FROM public.roles;
-- Deve mostrar 3 roles: user, admin, moderator
