-- ============================================================================
-- Migration: Create User Trigger
-- Description: Trigger automático que cria registro em public.users ao signup
-- Author: Generated by AI Coding Process
-- Date: 2024-01-01
-- ============================================================================

-- ============================================================================
-- Function: Criar perfil público ao criar usuário no auth
-- ============================================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  default_role_id UUID;
BEGIN
  -- Buscar o ID do role 'user' (role padrão)
  SELECT id INTO default_role_id
  FROM public.roles
  WHERE name = 'user'
  LIMIT 1;

  -- Se não encontrar role 'user', lançar erro
  IF default_role_id IS NULL THEN
    RAISE EXCEPTION 'Role padrão "user" não encontrado. Execute migration de roles primeiro.';
  END IF;

  -- Criar perfil público do usuário
  INSERT INTO public.users (
    auth_id,
    role_id,
    name,
    avatar_url
  ) VALUES (
    NEW.id,
    default_role_id,
    COALESCE(NEW.raw_user_meta_data->>'name', NEW.email),
    NEW.raw_user_meta_data->>'avatar_url'
  );

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Comentário na function
COMMENT ON FUNCTION handle_new_user() IS 'Cria automaticamente registro em public.users quando usuário faz signup';

-- ============================================================================
-- Trigger: Executar handle_new_user após signup
-- ============================================================================
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

COMMENT ON TRIGGER on_auth_user_created ON auth.users IS 'Trigger que cria perfil público automaticamente';

-- ============================================================================
-- Verificação
-- ============================================================================
-- Para testar:
-- 1. Crie um usuário via Supabase Auth (signup)
-- 2. Execute: SELECT * FROM public.users;
-- 3. Deve aparecer automaticamente com role 'user'
--
-- Teste manual (NÃO fazer em produção):
-- INSERT INTO auth.users (
--   instance_id,
--   id,
--   aud,
--   role,
--   email,
--   encrypted_password,
--   email_confirmed_at,
--   raw_user_meta_data,
--   created_at,
--   updated_at
-- ) VALUES (
--   '00000000-0000-0000-0000-000000000000',
--   gen_random_uuid(),
--   'authenticated',
--   'authenticated',
--   'test@example.com',
--   crypt('password123', gen_salt('bf')),
--   NOW(),
--   '{"name": "Test User"}',
--   NOW(),
--   NOW()
-- );
--
-- Depois verifique: SELECT * FROM public.users WHERE name = 'Test User';
