-- ============================================================================
-- Migration: Create Helper Functions
-- Description: Funções úteis para o sistema
-- Author: Generated by AI Coding Process
-- Date: 2024-01-01
-- ============================================================================

-- ============================================================================
-- Function: Verificar se usuário é admin
-- ============================================================================
CREATE OR REPLACE FUNCTION is_admin(user_id UUID)
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.users u
    JOIN public.roles r ON u.role_id = r.id
    WHERE u.auth_id = user_id AND r.name = 'admin'
  );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION is_admin(UUID) IS 'Verifica se um usuário tem papel de admin';

-- ============================================================================
-- Function: Obter perfil completo do usuário
-- ============================================================================
CREATE OR REPLACE FUNCTION get_user_profile(user_id UUID)
RETURNS TABLE (
  id UUID,
  auth_id UUID,
  email TEXT,
  name TEXT,
  avatar_url TEXT,
  bio TEXT,
  role_name TEXT,
  permissions JSONB,
  created_at TIMESTAMPTZ
)
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  SELECT
    u.id,
    u.auth_id,
    a.email,
    u.name,
    u.avatar_url,
    u.bio,
    r.name as role_name,
    r.permissions,
    u.created_at
  FROM public.users u
  JOIN auth.users a ON u.auth_id = a.id
  JOIN public.roles r ON u.role_id = r.id
  WHERE u.auth_id = user_id;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION get_user_profile(UUID) IS 'Retorna perfil completo do usuário incluindo role e permissões';

-- ============================================================================
-- Function: Atualizar último acesso
-- ============================================================================
CREATE OR REPLACE FUNCTION update_last_access()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.users
  SET last_access_at = NOW()
  WHERE auth_id = auth.uid();
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION update_last_access() IS 'Atualiza o timestamp de último acesso do usuário';

-- ============================================================================
-- Function: Verificar permissão
-- ============================================================================
CREATE OR REPLACE FUNCTION has_permission(user_id UUID, permission TEXT)
RETURNS BOOLEAN
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_permissions JSONB;
BEGIN
  -- Buscar permissões do usuário
  SELECT r.permissions INTO user_permissions
  FROM public.users u
  JOIN public.roles r ON u.role_id = r.id
  WHERE u.auth_id = user_id;

  -- Se não encontrar usuário, retornar false
  IF user_permissions IS NULL THEN
    RETURN FALSE;
  END IF;

  -- Verificar se tem a permissão específica
  RETURN (user_permissions ->> permission)::BOOLEAN = TRUE;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION has_permission(UUID, TEXT) IS 'Verifica se usuário tem uma permissão específica';

-- ============================================================================
-- Atualizar policies de roles com função is_admin
-- ============================================================================

-- Remover policy antiga se existir
DROP POLICY IF EXISTS "Only admins can modify roles" ON public.roles;

-- Policy: Apenas admins podem modificar roles
CREATE POLICY "Only admins can modify roles"
  ON public.roles FOR ALL
  USING (is_admin(auth.uid()));

-- ============================================================================
-- Policy adicional para users: Admins podem ver todos
-- ============================================================================
CREATE POLICY "Admins can see all users"
  ON public.users FOR SELECT
  USING (is_admin(auth.uid()));

CREATE POLICY "Admins can update any user"
  ON public.users FOR UPDATE
  USING (is_admin(auth.uid()));

CREATE POLICY "Admins can delete users"
  ON public.users FOR DELETE
  USING (is_admin(auth.uid()));

-- ============================================================================
-- Verificação
-- ============================================================================
-- Testar as funções:
--
-- 1. Verificar se usuário atual é admin:
-- SELECT is_admin(auth.uid());
--
-- 2. Obter perfil completo:
-- SELECT * FROM get_user_profile(auth.uid());
--
-- 3. Verificar permissão específica:
-- SELECT has_permission(auth.uid(), 'write');
--
-- 4. Promover um usuário a admin (como admin):
-- UPDATE public.users
-- SET role_id = (SELECT id FROM public.roles WHERE name = 'admin')
-- WHERE auth_id = '[user-uuid]';
