-- ============================================================================
-- Migration: Create Users Table
-- Description: Cria tabela de users estendendo auth.users
-- Author: Generated by AI Coding Process
-- Date: 2024-01-01
-- ============================================================================

-- Criar tabela de users (perfil público)
CREATE TABLE IF NOT EXISTS public.users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id UUID NOT NULL REFERENCES public.roles(id),
  name TEXT NOT NULL,
  avatar_url TEXT,
  bio TEXT,
  last_access_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Comentários na tabela
COMMENT ON TABLE public.users IS 'Perfis públicos dos usuários, estende auth.users';
COMMENT ON COLUMN public.users.auth_id IS 'Referência para auth.users (Supabase Auth)';
COMMENT ON COLUMN public.users.role_id IS 'Papel do usuário no sistema';
COMMENT ON COLUMN public.users.name IS 'Nome de exibição do usuário';
COMMENT ON COLUMN public.users.last_access_at IS 'Último acesso do usuário';

-- Índices
CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_id);
CREATE INDEX IF NOT EXISTS idx_users_role_id ON public.users(role_id);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON public.users(created_at);

-- ============================================================================
-- Function: Atualizar updated_at automaticamente
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para atualizar updated_at
DROP TRIGGER IF EXISTS update_users_updated_at ON public.users;
CREATE TRIGGER update_users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Row Level Security (RLS)
-- ============================================================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Policy 1: Usuários podem ler próprio perfil
CREATE POLICY "Users can read own profile"
  ON public.users FOR SELECT
  USING (auth_id = auth.uid());

-- Policy 2: Usuários podem atualizar próprio perfil (mas NÃO podem mudar role_id)
CREATE POLICY "Users can update own profile"
  ON public.users FOR UPDATE
  USING (auth_id = auth.uid())
  WITH CHECK (
    auth_id = auth.uid() AND
    role_id = (SELECT role_id FROM public.users WHERE auth_id = auth.uid())
  );

-- Policy 3: Usuários podem ler perfis públicos (informações básicas)
CREATE POLICY "Users can read public profiles"
  ON public.users FOR SELECT
  USING (true);

-- ============================================================================
-- Verificação
-- ============================================================================
-- A tabela deve estar criada mas vazia (usuários serão criados via trigger)
-- SELECT * FROM public.users;
